name: Build Windows EXE

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install pyinstaller keyboard openpyxl
          
      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed --icon=icono.ico --name "Contador de Tramites" contador.py
          
      - name: Create or update Release
        uses: ncipollo/release-action@v1
        with:
          tag: "latest"
          name: "Ultima version"
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "dist/Contador de Tramites.exe"
          token: ${{ secrets.GITHUB_TOKEN }}
